spring.application.name=SideProject01Bissol
server.port=9000

# --- Oracle ---
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=BISSOL
spring.datasource.password=1234

# --- JPA ---
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# --- Swagger ---
springdoc.api-docs.enabled=true 
springdoc.paths-to-match=/**
springdoc.packages-to-scan=com.example.sideproject01

# --- JSON ---
spring.jackson.time-zone=Asia/Seoul

# --- SQL Init ---
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8

# ??? ??? ????
spring.servlet.multipart.max-file-size=500MB
# ??? ??? ????(??? ?? + ????? ???)
spring.servlet.multipart.max-request-size=600MB


# ✅ Oracle 11g(XE 11.2)용 Dialect 강제 (FETCH FIRST 방지)
#spring.jpa.database-platform=org.hibernate.community.dialect.Oracle10gDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.Oracle10gDialect



